Rodrigo
grupo-rovema-new/sap-sql-sovis pull request #5
Opened 2024-04-11 20:29 UTC by rodrigocesar87

TESTE DE MUDANÇA

2024-04-11 20:49 UTC, franciscoMarcello requested changes
Select vai falhar

2024-04-16 15:39 UTC, franciscoMarcello approved these changes

2024-04-16 18:45 UTC, malacration commented
O nome do merge request nao condiz com o que esta sendo executado, porfavor realize a mudanca!

2024-04-16 18:49 UTC, malacration approved these changes

2024-04-16 18:49 UTC, malacration commented on src/views/financeiro/VALORINICIAL.sql
Nao pode ter SBOGRUPOROVEMAS na view! Quem controla o esquema e o script python

2024-04-16 19:20 UTC, rodrigocesar87 commented on src/views/financeiro/VALORINICIAL.sql
Estarei fazendo a alteração

2024-04-16 21:22 UTC, franciscoMarcello reviewed
Acredito que tenha resolvido o problema.

2024-04-17 19:00 UTC, franciscoMarcello approved these changes

2024-04-17 19:05 UTC, franciscoMarcello approved these changes

2024-04-17 19:09 UTC, merged